language: node_js
node_js:
- '8'
sudo: false
branches:
  only:
  - master
  - development 
  - /^v\d+\.\d+(\.\d+)?(-\S*)?$/
before_install:
- rm -f ${TRAVIS_BUILD_DIR}/yarn.lock
- npm config set //registry.npmjs.org/:_authToken=$NPM_TOKEN
jobs:
  include:
  - stage: Unit tests
    env:
    - DESCRIPTION=LINTER
    script: "./travis_scripts/linter.sh"
  - env:
    - DESCRIPTION=UNIT_TEST
    script: "./travis_scripts/unit-tests.sh"
  - stage: Build Staging
    env:
    - NODE_ENV=production
    - PORT=12345
    - MARKETPLACE_API_URL=https://www.streamr.com/api/v1/
    - STREAMR_WS_URL=wss://www.streamr.com/api/v1/ws
    - STREAMR_URL=https://www.streamr.com/
    - MARKETPLACE_URL=https://variotram.streamr.com
    - GOOGLE_ANALYTICS_ID=55331565-5
    script: "./travis_scripts/build-app-stg.sh"
    deploy:
    - provider: s3
      access_key_id: AKIAIOJ3P2HUF42UCGZA
      secret_access_key:
        secure: hXyXFR/L3HeQZEPxk9gztcz4/756sSqdq5aoSvpBecNp7A1Vz6spP1gP8TszKN24G8FtzBnMO+u2Ff8EzeBqhzVncudhg/XJV7i7Fpiffytm3aGkYMuhxI6GHIw7LU6liSvVQSk0ZnCUr079ZoO3gTKsapuAn2+WLuSNMTYHaTCwf5pbTJ+EINaKT/LzrJz17Kd804WGyHkEZsyQLFfkXZ9LDtHPSGNIsl0hua6gBNJc7QNXcjNg6sXKMZoYe2ONbJSxE30ftRr/8n+ThvAHP5/0RSAi0wsNt60LVZbD6mFPRzWbyJA+X08WjgjNlKN45S3FIR/yQsyygUNbcwJC12mpN2ubYrt9OqYH0z/aCmb4gILVcf37tcXxsI0F1YfRKNfSfeCF1U6bh78ly430GojdZNa1zsfdCnIV6lGwccXEyCSeTfy+S30gJp7fN2z4NRixMI4yxtqO2g8I9769Zi/+zXrsl1tVZysfEyzVOwgP5ODQb20tJ9Y5aYTv6VsJT+rFs6wcqTppOJb9NVtYV2MgMwkF//aOT6+HwnUnMaAbiNNep/V40YSn8/iEh+L3xsm1FnYr6GYOSpELbO1m+/yU/T3bHglv0odttE575/BkBpP3i7kXouirHNsukQiVG1hwCHq5PPxgU8z/MWpLprW7zcls0QL1gfndgdbdwAk=
      bucket: eu-west-1-stg-streamr-marketplace-public
      local-dir: dist
      acl: private
      region: eu-west-1
      skip_cleanup: true
      on:
        tags: false
  - stage: Build Production
    if: NOT type IN (pull_request)
    env:
    - NODE_ENV=production
    - PORT=12345
    - MARKETPLACE_API_URL=https://www.streamr.com/api/v1
    - STREAMR_WS_URL=wss://www.streamr.com/api/v1/ws
    - STREAMR_URL=https://www.streamr.com/
    - MARKETPLACE_URL=https://marketplace.streamr.com
    - GOOGLE_ANALYTICS_ID=55331565-5
    script: "./travis_scripts/build-app.sh"
    deploy:
    - provider: s3
      access_key_id: AKIAIOJ3P2HUF42UCGZA
      secret_access_key:
        secure: hXyXFR/L3HeQZEPxk9gztcz4/756sSqdq5aoSvpBecNp7A1Vz6spP1gP8TszKN24G8FtzBnMO+u2Ff8EzeBqhzVncudhg/XJV7i7Fpiffytm3aGkYMuhxI6GHIw7LU6liSvVQSk0ZnCUr079ZoO3gTKsapuAn2+WLuSNMTYHaTCwf5pbTJ+EINaKT/LzrJz17Kd804WGyHkEZsyQLFfkXZ9LDtHPSGNIsl0hua6gBNJc7QNXcjNg6sXKMZoYe2ONbJSxE30ftRr/8n+ThvAHP5/0RSAi0wsNt60LVZbD6mFPRzWbyJA+X08WjgjNlKN45S3FIR/yQsyygUNbcwJC12mpN2ubYrt9OqYH0z/aCmb4gILVcf37tcXxsI0F1YfRKNfSfeCF1U6bh78ly430GojdZNa1zsfdCnIV6lGwccXEyCSeTfy+S30gJp7fN2z4NRixMI4yxtqO2g8I9769Zi/+zXrsl1tVZysfEyzVOwgP5ODQb20tJ9Y5aYTv6VsJT+rFs6wcqTppOJb9NVtYV2MgMwkF//aOT6+HwnUnMaAbiNNep/V40YSn8/iEh+L3xsm1FnYr6GYOSpELbO1m+/yU/T3bHglv0odttE575/BkBpP3i7kXouirHNsukQiVG1hwCHq5PPxgU8z/MWpLprW7zcls0QL1gfndgdbdwAk=
      bucket: eu-west-1-streamr-marketplace-public
      local-dir: dist
      acl: private
      region: eu-west-1
      skip_cleanup: true
      on:
        tags: true
    - provider: s3
      access_key_id: AKIAIOJ3P2HUF42UCGZA
      secret_access_key:
        secure: hXyXFR/L3HeQZEPxk9gztcz4/756sSqdq5aoSvpBecNp7A1Vz6spP1gP8TszKN24G8FtzBnMO+u2Ff8EzeBqhzVncudhg/XJV7i7Fpiffytm3aGkYMuhxI6GHIw7LU6liSvVQSk0ZnCUr079ZoO3gTKsapuAn2+WLuSNMTYHaTCwf5pbTJ+EINaKT/LzrJz17Kd804WGyHkEZsyQLFfkXZ9LDtHPSGNIsl0hua6gBNJc7QNXcjNg6sXKMZoYe2ONbJSxE30ftRr/8n+ThvAHP5/0RSAi0wsNt60LVZbD6mFPRzWbyJA+X08WjgjNlKN45S3FIR/yQsyygUNbcwJC12mpN2ubYrt9OqYH0z/aCmb4gILVcf37tcXxsI0F1YfRKNfSfeCF1U6bh78ly430GojdZNa1zsfdCnIV6lGwccXEyCSeTfy+S30gJp7fN2z4NRixMI4yxtqO2g8I9769Zi/+zXrsl1tVZysfEyzVOwgP5ODQb20tJ9Y5aYTv6VsJT+rFs6wcqTppOJb9NVtYV2MgMwkF//aOT6+HwnUnMaAbiNNep/V40YSn8/iEh+L3xsm1FnYr6GYOSpELbO1m+/yU/T3bHglv0odttE575/BkBpP3i7kXouirHNsukQiVG1hwCHq5PPxgU8z/MWpLprW7zcls0QL1gfndgdbdwAk=
      bucket: eu-west-1-streamr-vault
      local-dir: dist
      upload-dir: marketplace/releases/latest
      acl: private
      region: eu-west-1
      skip_cleanup: true
      on:
        tags: false
    - provider: s3
      access_key_id: AKIAIOJ3P2HUF42UCGZA
      secret_access_key:
        secure: hXyXFR/L3HeQZEPxk9gztcz4/756sSqdq5aoSvpBecNp7A1Vz6spP1gP8TszKN24G8FtzBnMO+u2Ff8EzeBqhzVncudhg/XJV7i7Fpiffytm3aGkYMuhxI6GHIw7LU6liSvVQSk0ZnCUr079ZoO3gTKsapuAn2+WLuSNMTYHaTCwf5pbTJ+EINaKT/LzrJz17Kd804WGyHkEZsyQLFfkXZ9LDtHPSGNIsl0hua6gBNJc7QNXcjNg6sXKMZoYe2ONbJSxE30ftRr/8n+ThvAHP5/0RSAi0wsNt60LVZbD6mFPRzWbyJA+X08WjgjNlKN45S3FIR/yQsyygUNbcwJC12mpN2ubYrt9OqYH0z/aCmb4gILVcf37tcXxsI0F1YfRKNfSfeCF1U6bh78ly430GojdZNa1zsfdCnIV6lGwccXEyCSeTfy+S30gJp7fN2z4NRixMI4yxtqO2g8I9769Zi/+zXrsl1tVZysfEyzVOwgP5ODQb20tJ9Y5aYTv6VsJT+rFs6wcqTppOJb9NVtYV2MgMwkF//aOT6+HwnUnMaAbiNNep/V40YSn8/iEh+L3xsm1FnYr6GYOSpELbO1m+/yU/T3bHglv0odttE575/BkBpP3i7kXouirHNsukQiVG1hwCHq5PPxgU8z/MWpLprW7zcls0QL1gfndgdbdwAk=
      bucket: eu-west-1-streamr-vault
      local-dir: dist
      upload-dir: marketplace/releases/$TRAVIS_TAG
      acl: private
      region: eu-west-1
      skip_cleanup: true
      on:
        tags: true
    - provider: script
      script: bash travis_scripts/sentry-release.sh
      skip_cleanup: true
      on:
        tags: true
env:
  global:
  - secure: qJIG/9LEmO4+vRWHeDfc4JatL9ra/jJYZYekgw4p1F0GEGuGCIOH2+HtiMnjB/KP6tKUIkcg3/yQM31FszY7QgpzeNo2Ntlzlebqhyn9GUD80Jir3+U6QqTkaVuA1ogg37DA0z1yBz7+KGKmU4h/ESzMG03iuquOqBei2fco56LAjjzZ+W1UwhGumOr2ADKXqjU7hsYR6gSqTF4ygeoL4OOqRvXpQhTuSkm7yGDDJQlpgvesjTBpAVyTZoNTLTY6wmDpBLFGj/+ir9uAXEclDqlTY4mxq4aAkgNVFEMLiaD1hLea9rDaaYQI+DOOGFEO2sBKQNXUDNfbPnybhG4WZFVSZWV0YvD8XrGRPzJqOe+QJNeuhSG9D33fFlTFBR4mvuJqzadu11RVTsVxxSNWeAEE2HDbuIJPPK0STEioyqPU7Svz/vkpQ7d0LcfKCajQXeVLJCfhMHEngTvs3pkB1oDBu/oUDywRCdMX7PJ1h+sy8+oy4fHTafgKKVZ2uN84HD/TDyO9P2uonUBK5tReLYduP2j+5y5EZS82eNXvaq8ITMsnkBUE/2QCvKdqicTHIzlRsTAV8dwhC1qPF69jH7FTVJX2rjKao9IjbysjC6WaAsTBz4lR7iAKu9Qw66opdlGED29EBHmMagnBBMEW5qyk+6OFdxCk9zZ5FuXUkrA=
  - secure: bAmVHzeCC1KdhmAX8i7nJ69YNga87jUARIhT9AY1vu70hBAd6KkrZVsyO5PltAfxO/xit/S2qxhTAKYg/5tLYNDWhc2nMk0wmEFZZRV6GNyzZxQjBw/US6DSqicWs/CUigL9fo8ECZJiFx9ZPwAP+2kzeDBb6+3LYeAGMy6UdkVoriboTIMYYIVDyXoL1Qu8MBFbNONoAR4a/sEiB0KDQKFgIjRPiejZFRfLPYG4hRY/1VNxGkGJF9dpmiqPRp8CM0+9ZlReQc0vQVR+wk7Dq7Hq1b3ppC0rENitUimrggJ7V5RleDBdLxj5VcVQOaL7tz31xmnpNpRSrrxx9Nc6K5sqIlKrImhLfI8IWEcgr+v06h3JeXsTZMkBJlE6k9nFvCkJoiw8bAZU2tqe9RheevkJAlhxrSWn4ql9ZwNuFBYkFp1N9FoQ5Sp0WtecVxdc2BZjr9oqUGp6QYXMWpQe6omaFd8IteySknl9H35mJmDF58a8qiK8X9tz2vedAkmPS8G+UNhpaFNLQGJUYU4wMogycPz904TlaQmZKL0UuYA2gSqV6npxpxp4I951m4uBt6wlNpg2GQBmgKYkgyxhBh3L7PO0sMsr8c/5/XPXSvpMZELC00LA6INGbILizwacK9hdIeTDwGNr0OvL+8KkTCs9KZ27cN7qM0fxKPQCX5c=
notifications:
  slack:
    secure: DvIa9HP8+ef4mOmxhJUXkliJ2tgZ2ACME9wxyXz5ZB2SsGzJn+qyft9I6wYpI9MAey0YI1QJXLc1dbGNLP1+08VgeC7t2BfaD7kNBllrG53VVrihFIgw7ZLnJHEUCXrJR7Ilygicc4wzzvGD6hrzcNU1zqA41wSTRdh50CsUviAOx0no3E6nXt4Q2mmOCfLDNIUyhsO+PmGaqOTM1BnyUwkIrDPHffGcYXCh+E49AMBfMwkgr/EWRU/6j04eftOPe5qCu32V1ldl0BUC45zqT8k1jC/muz2YoCM79IVVXoUM7nBKJPTaiqvm5a+uQdCU1lBz2PhWRgkwD+vWewJz4Ff/HQOl5cop4d1vkHMMtBhP9iUsPuDNIskk91E5mcq6WIaj3ZjK7fMCdr6dYYQqW9J5dRqcCrZ7jTejlopgPPJN7cefy1jInBqO+jfaPGsGdmWEhblTRJuYZDCKfuFhZKbqEKCxwD1F2VMefhlXaKmnwK5LuIjwTlT2LyyCtOB8biw9pV0LhlD5IFdqNIWpuXLcrMeQqVM1uVbNiIC7w+RYDRvXdZ8XxVbTJBD1Ytbf4xHNg5ELNYxYgDUT3ULKWIw9TjNiP0s7DBcJmeJFGh3Gx6UDaLtDDzhNc9WZT2wkVsAwPr5BDVv6C3p8gCQT8l1SXmg6ZjxFETITr2KR5nw=
  on_success: change
  on_failure: always
  on_pull_requests: false
